"""empty message

Revision ID: 0247ec800c7b
Revises: ee935258a72f
Create Date: 2021-12-17 14:16:55.859891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0247ec800c7b'
down_revision = 'ee935258a72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slug_reservation', sa.Column('synced', sa.Boolean(), nullable=True))
    op.add_column('url_entry_model', sa.Column('synced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_entry_model', 'synced')
    op.drop_column('slug_reservation', 'synced')
    # ### end Alembic commands ###
