"""empty message

Revision ID: b0d362d73a3f
Revises: 
Create Date: 2021-09-19 14:38:42.918199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d362d73a3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_entry_model',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('longUrl', sa.String(), nullable=True),
    sa.Column('used', sa.BIGINT(), nullable=True),
    sa.Column('lastUsed', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_entry_model')
    # ### end Alembic commands ###
