"""Initial migration.

Revision ID: c31c1eaabd08
Revises: 
Create Date: 2021-09-18 22:06:18.396255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31c1eaabd08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_entry_model',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('longUrl', sa.String(), nullable=True),
    sa.Column('used', sa.BIGINT(), nullable=True),
    sa.Column('lastUsed', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_entry_model')
    # ### end Alembic commands ###
